[pipeline-feature-selection]
high_cardinality_from_eda = [ "title", "city",]
categoricals_more_than_threshold = [ "attribute_group_id", "attribute_group", "attribute_id",]
categoricals_less_than_threshold = [ "state", "city",]
categoricals_high_cardinality = [ "state", "city", "listing_type", "attribute_group_id", "attribute_group", "attribute_id", "title",]
categoricals_low_cardinality = [ "local_pickup", "free_shipping", "shipping_mode", "buying_mode", "status", "accepts_mercadopago", "currency", "automatic_relist",]

[pipeline-feature-engineering]
categoricals_less_than_threshold = [ "state",]
categoricals_high_cardinality = [ "state", "listing_type",]
categoricals_low_cardinality = [ "local_pickup", "shipping_mode",]

[pipeline-params]
n_cat_high = 2
n_cat_low = 2
bins = 8

[xgb-default-params]
objective = "binary:logistic"
eta = 0.1
eval_metric = [ "auc", "logloss",]
seed = 25
device = "cuda"

[xgb-tunned-params]
max_depth = 7
learning_rate = 0.00430717491483756
min_child_weight = 4
subsample = 0.8377009078022873
colsample_bytree = 0.7144793051992504
reg_alpha = 0.0017293439632290603
reg_lambda = 0.0010064837170065289
