[pipeline-feature-selection]
high_cardinality_from_eda = [ "title", "city",]
categoricals_more_than_threshold = [ "attribute_group_id", "attribute_group", "attribute_id",]
categoricals_less_than_threshold = [ "state", "city",]
categoricals_high_cardinality = [ "state", "city", "listing_type", "attribute_group_id", "attribute_group", "attribute_id", "title",]
categoricals_low_cardinality = [ "local_pickup", "free_shipping", "shipping_mode", "buying_mode", "status", "accepts_mercadopago", "currency", "automatic_relist",]

[pipeline-feature-engineering]
categoricals_less_than_threshold = [ "state",]
categoricals_high_cardinality = [ "state", "listing_type",]
categoricals_low_cardinality = [ "local_pickup", "shipping_mode",]

[pipeline-params]
n_cat_high = 2
n_cat_low = 2
bins = 8

[xgb-default-params]
objective = "binary:logistic"
eta = 0.1
eval_metric = [ "auc", "logloss",]
seed = 25
device = "cuda"

[xgb-tuned-params]
objective = "binary:logistic"
eval_metric = [ "auc", "logloss",]
seed = 25
device = "cuda"
max_depth = 6
learning_rate = 0.09945811829216437
min_child_weight = 3
subsample = 0.9603898382520749
colsample_bytree = 0.7536836580146604
reg_alpha = 0.09884773595219716
reg_lambda = 0.0065655223184726995
num_boosted_rounds = 93
