features:
  seller_address_country: country
  seller_address_state: state
  seller_address_city: city
  condition: target
  base_price: price
  shipping_local_pick_up: local_pickup
  shipping_free_shipping: free_shipping
  shipping_mode: shipping_mode
  seller_id: seller_id
  site_id: site_id
  listing_type_id: listing_type
  attr_attribute_group_id: attribute_group_id
  attr_name: attribute_name
  attr_attribute_group_name: attribute_group
  attr_id: attribute_id
  buying_mode: buying_mode
  category_id: category_id
  last_updated: last_updated
  product_id: product_id
  accepts_mercadopago: accepts_mercadopago
  currency_id: currency
  title: title
  automatic_relist: automatic_relist
  date_created: date_created
  stop_time: stop_time
  status: status
  initial_quantity: initial_quantity
  start_time: start_time
  sold_quantity: sold_quantity
  available_quantity: available_quantity
